# Generated by Django 2.2.3 on 2019-07-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20190714_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_stu_id', models.CharField(max_length=20, verbose_name='学号')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Student')),
            ],
        ),
    ]
